


--FUNCTION TO GET TOTAL PRICE OF A CART


CREATE OR REPLACE FUNCTION TOTAL_PRICE
(CART_ID1 Varchar2) 
RETURN NUMBER  
IS
Total_PRIC  Number(10);
BEGIN
        SELECT SUM(DISCOUNTED_PRICE) INTO Total_PRIC FROM PRODUCT P INNER JOIN CART_PRODUCT CP ON P.PRODUCT_ID = CP.PRODUCT_ID 
        WHERE CART_ID LIKE CART_ID1;  

        RETURN Total_PRIC ;
END TOTAL_PRICE; 

--FUNCTION TO CHECK CART AND PRODUCT
CREATE OR REPLACE FUNCTION CHECK1(CART_ID1	VARCHAR2,PRODUCT_ID1 VARCHAR2)
RETURN VARCHAR  
IS
C1 VARCHAR(50);
C2 VARCHAR(10);
BEGIN
        SELECT PRODUCT_NAME INTO C1 FROM PRODUCT WHERE PRODUCT_ID = PRODUCT_ID1 AND QUANTITY>0; 
        SELECT CUSTOMER_ID INTO C1 FROM CART WHERE CART_ID = CART_ID1 AND UPPER(CART_STATUS) LIKE 'ACTIVE'; 
        
        RETURN 'OK' ;
        EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'NOT OK';
END CHECK1; 



--TO ADD/DELETE ON CART_PRODUCT TABLE AND UPDATE TOTAL PRICE IN CART TABLE AND QUANTITY IN PRODUCT TABLE
CREATE OR REPLACE PROCEDURE ADD_OR_DELETE_CART_PRODUCT(CART_ID1	VARCHAR2,PRODUCT_ID1 VARCHAR2,TY VARCHAR)
IS
    v_NUM NUMBER;
    NUM1 NUMBER;
    NUM2 NUMBER;
    count1 number;
    CH2 VARCHAR2(10);
    CH3 VARCHAR(100);
BEGIN
    CH2 := CHECK1(CART_ID1,PRODUCT_ID1);
    IF CH2 LIKE 'OK' THEN
        IF UPPER(TY) LIKE 'ADD' THEN
            INSERT INTO CART_PRODUCT VALUES (CART_ID1,PRODUCT_ID1);
            V_NUM := TOTAL_PRICE(CART_ID1);
            SELECT QUANTITY INTO count1 FROM PRODUCT WHERE PRODUCT_ID = PRODUCT_ID1;
            update product set QUANTITY=(count1-1)where PRODUCT_ID = PRODUCT_ID1;
            UPDATE CART SET TOTAL_PRICE = V_NUM WHERE CART_ID LIKE CART_ID1;
        ELSIF UPPER(TY) LIKE 'DELETE' THEN
            SELECT ROWID INTO CH3 FROM CART_PRODUCT WHERE CART_ID LIKE CART_ID1 AND PRODUCT_ID LIKE PRODUCT_ID1 FETCH FIRST ROW ONLY;
            DELETE FROM CART_PRODUCT WHERE ROWID LIKE CH3;
            SELECT TOTAL_PRICE INTO NUM1 FROM CART WHERE CART_ID LIKE CART_ID1;
            SELECT DISCOUNTED_PRICE INTO NUM2 FROM  PRODUCT WHERE PRODUCT_ID LIKE PRODUCT_ID1;
            UPDATE CART SET TOTAL_PRICE = NUM1-NUM2 WHERE CART_ID LIKE CART_ID1;
            SELECT QUANTITY INTO count1 FROM PRODUCT WHERE PRODUCT_ID = PRODUCT_ID1;
            update product set QUANTITY=(count1+1)where PRODUCT_ID = PRODUCT_ID1;
        ELSE
            DBMS_OUTPUT.PUT_LINE('ENTER RIGHT COMMAND' );
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('PRODUCT OR CART NOT AVALABLE' );
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE ('PRODUCT NOT AVAILABLE IN CART');
    
END ADD_OR_DELETE_CART_PRODUCT;