-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-09-07 00:41:34 IST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cart (
    cart_id         VARCHAR2(10) NOT NULL,
    customer_id     VARCHAR2(10) NOT NULL,
    total_price     NUMBER(30),
    delivery_status CHAR(200)
)
LOGGING;

ALTER TABLE cart ADD CONSTRAINT pk_cartid PRIMARY KEY ( cart_id );

CREATE TABLE cart_payment (
    cart_id    VARCHAR2(10) NOT NULL,
    payment_id NUMBER(10) NOT NULL
)
LOGGING;

ALTER TABLE cart_payment ADD CONSTRAINT pk_cartpayment PRIMARY KEY ( cart_id,
                                                                     payment_id );

CREATE TABLE cart_product (
    cart_id    VARCHAR2(10) NOT NULL,
    product_id VARCHAR2(10) NOT NULL
)
LOGGING;

CREATE TABLE categories (
    category_id   NUMBER(10) NOT NULL,
    category_name VARCHAR2(100),
    subcategory   VARCHAR2(20),
    image         BLOB
)
LOGGING;

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY ( category_id );

CREATE TABLE customer (
    customer_id VARCHAR2(10) NOT NULL,
    first_name  VARCHAR2(20)
        CONSTRAINT firstname_notnull NOT NULL,
    last_name   VARCHAR2(30),
    image       BLOB,
    address     VARCHAR2(100),
    phone       VARCHAR2(15)
        CONSTRAINT cust_phone_uq NOT NULL,
    email       VARCHAR2(30),
    dateofbirth VARCHAR2(10),
    country     VARCHAR2(10),
    postal_code NUMBER(20),
    city        VARCHAR2(10),
    state       VARCHAR2(10)
)
LOGGING;

ALTER TABLE customer ADD CONSTRAINT pk_customerid PRIMARY KEY ( customer_id );

ALTER TABLE customer ADD CONSTRAINT address_uq UNIQUE ( address );

ALTER TABLE customer ADD CONSTRAINT email_uq UNIQUE ( email );

ALTER TABLE customer ADD CONSTRAINT index_1 UNIQUE ( phone );

CREATE TABLE login_details (
    login_id  VARCHAR2(10) NOT NULL,
    password  VARCHAR2(50) NOT NULL,
    user_type VARCHAR2(20) NOT NULL
)
LOGGING;

ALTER TABLE login_details ADD CONSTRAINT pk_login_details PRIMARY KEY ( login_id );

CREATE TABLE membership (
    membership_type VARCHAR2(20) NOT NULL,
    user_id         VARCHAR2(10) NOT NULL,
    start_date      DATE,
    duration        NUMBER(10)
)
LOGGING;

CREATE TABLE payment (
    payment_id     NUMBER(10) NOT NULL,
    customer_id    VARCHAR2(10) NOT NULL,
    payment_amount NUMBER(30),
    payment_mode   VARCHAR2(20)
        CONSTRAINT paymentmode_notnull NOT NULL,
    payment_date   DATE
        CONSTRAINT paymentdate_notnull NOT NULL,
    payment_status CHAR(200)
        CONSTRAINT paymentstatus_notnull NOT NULL
)
LOGGING;

ALTER TABLE payment ADD CONSTRAINT pk_paymentid PRIMARY KEY ( payment_id );

CREATE TABLE product (
    product_id       VARCHAR2(10) NOT NULL,
    category_id      NUMBER(10)
        CONSTRAINT category_notnull NOT NULL,
    product_name     VARCHAR2(50)
        CONSTRAINT productname_notnull NOT NULL,
    brand            VARCHAR2(20),
    quantity         NUMBER NOT NULL,
    price            NUMBER(8, 2)
        CONSTRAINT price_notnull NOT NULL,
    discount         INTEGER,
    discounted_price NUMBER(8, 2),
    description      VARCHAR2(100),
    image            BLOB
)
LOGGING;

ALTER TABLE product
    ADD CONSTRAINT discount_percent CHECK ( discount >= 0
                                            AND discount < 100 );

ALTER TABLE product ADD CONSTRAINT pk_productid PRIMARY KEY ( product_id );

CREATE TABLE product_seller (
    product_id VARCHAR2(10) NOT NULL,
    seller_id  VARCHAR2(10) NOT NULL
)
LOGGING;

ALTER TABLE product_seller ADD CONSTRAINT pk_productseller PRIMARY KEY ( product_id,
                                                                         seller_id );

CREATE TABLE review (
    product_id     VARCHAR2(10) NOT NULL,
    review_title   VARCHAR2(20)
        CONSTRAINT title_notnull NOT NULL,
    product_rating NUMBER(10),
    other_comments CHAR(200),
    customer_id    VARCHAR2(10) NOT NULL,
    review_date    VARCHAR2(10)
        CONSTRAINT reviewdate_notnull NOT NULL
)
LOGGING;

ALTER TABLE review
    ADD CONSTRAINT productrating_range CHECK ( product_rating >= 1
                                               AND product_rating <= 5 );

CREATE TABLE seller (
    seller_id     VARCHAR2(10) NOT NULL,
    seller_name   VARCHAR2(20)
        CONSTRAINT sellername_notnull NOT NULL,
    seller_rating NUMBER(10),
    phone         VARCHAR2(15)
        CONSTRAINT seller_phone_uq NOT NULL
)
LOGGING;

ALTER TABLE seller
    ADD CONSTRAINT sellerrating_range CHECK ( seller_rating >= 1
                                              AND seller_rating <= 5 );

ALTER TABLE seller ADD CONSTRAINT pk_sellerid PRIMARY KEY ( seller_id );

ALTER TABLE seller ADD CONSTRAINT index_1v1 UNIQUE ( phone );

ALTER TABLE cart
    ADD CONSTRAINT fk_cart_customerid FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE cart_product
    ADD CONSTRAINT fk_cart_product_cart_id FOREIGN KEY ( cart_id )
        REFERENCES cart ( cart_id )
    NOT DEFERRABLE;

ALTER TABLE cart_product
    ADD CONSTRAINT fk_cart_product_product_id FOREIGN KEY ( product_id )
        REFERENCES product ( product_id )
    NOT DEFERRABLE;

ALTER TABLE cart_payment
    ADD CONSTRAINT fk_cartid FOREIGN KEY ( cart_id )
        REFERENCES cart ( cart_id )
    NOT DEFERRABLE;

ALTER TABLE customer
    ADD CONSTRAINT fk_customer_login_details FOREIGN KEY ( customer_id )
        REFERENCES login_details ( login_id )
    NOT DEFERRABLE;

ALTER TABLE payment
    ADD CONSTRAINT fk_payment_customerid FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE cart_payment
    ADD CONSTRAINT fk_paymentid FOREIGN KEY ( payment_id )
        REFERENCES payment ( payment_id )
    NOT DEFERRABLE;

ALTER TABLE product_seller
    ADD CONSTRAINT fk_productid FOREIGN KEY ( product_id )
        REFERENCES product ( product_id )
    NOT DEFERRABLE;

ALTER TABLE review
    ADD CONSTRAINT fk_review_customerid FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE review
    ADD CONSTRAINT fk_review_productid FOREIGN KEY ( product_id )
        REFERENCES product ( product_id )
    NOT DEFERRABLE;

ALTER TABLE seller
    ADD CONSTRAINT fk_seller_login_details FOREIGN KEY ( seller_id )
        REFERENCES login_details ( login_id )
    NOT DEFERRABLE;

ALTER TABLE product_seller
    ADD CONSTRAINT fk_sellerid FOREIGN KEY ( seller_id )
        REFERENCES seller ( seller_id )
    NOT DEFERRABLE;

ALTER TABLE membership
    ADD CONSTRAINT membership_login_details_fk FOREIGN KEY ( user_id )
        REFERENCES login_details ( login_id )
    NOT DEFERRABLE;

ALTER TABLE product
    ADD CONSTRAINT product_categories_fk FOREIGN KEY ( category_id )
        REFERENCES categories ( category_id )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
